version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mcp
      POSTGRES_PASSWORD: mcp
      POSTGRES_DB: mcp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  minio-setup:
    image: minio/mc:RELEASE.2024-01-16T22-17-23Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "sleep 5 && mc alias set local http://minio:9000 minioadmin minioadmin && mc mb --ignore-existing local/mcp-audit && exit 0"

  otel-collector:
    image: otel/opentelemetry-collector:0.86.0
    command: ["--config", "/etc/otel/config.yaml"]
    volumes:
      - ../otel/collector-config.yaml:/etc/otel/config.yaml:ro
    ports:
      - "4318:4318"

  control-api:
    build:
      context: ..
      dockerfile: deploy/controlapi.Dockerfile
    depends_on:
      - postgres
      - minio
    environment:
      DATABASE_URL: postgresql+psycopg2://mcp:mcp@postgres:5432/mcp
      OIDC_ISSUER: http://control-api:8000/mock-issuer
      OIDC_AUDIENCE: mcp-clients
      PRIVATE_KEY_PATH: app/mock_rsa.pem
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: mcp-audit
    ports:
      - "8000:8000"

  gateway:
    build:
      context: ..
      dockerfile: deploy/gateway.Dockerfile
    depends_on:
      - control-api
      - redis
      - minio
      - hello-server
    environment:
      OIDC_ISSUER: http://control-api:8000/mock-issuer
      OIDC_AUDIENCE: mcp-clients
      JWKS_URL: http://control-api:8000/.well-known/jwks.json
      REDIS_URL: redis://redis:6379
      CONTROL_API_URL: http://control-api:8000
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: mcp-audit
      EGRESS_ALLOWLIST: ledger.api.corp,hello-server
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
    ports:
      - "8080:8080"

  admin-ui:
    build:
      context: ..
      dockerfile: deploy/adminui.Dockerfile
    depends_on:
      - control-api
      - gateway
    environment:
      VITE_CONTROL_API_URL: http://control-api:8000
      VITE_GATEWAY_URL: http://gateway:8080
    ports:
      - "5173:5173"

  hello-server:
    build:
      context: ../examples/mcp-servers/hello-server
    ports:
      - "4000:4000"

  conformance:
    build:
      context: ..
      dockerfile: deploy/conformance.Dockerfile
    command: ["sleep", "infinity"]
    depends_on:
      - gateway

volumes:
  postgres-data:
  minio-data:
